### ISSUE TITLE
Cmd not found

### ISSUE THREAD

**Issue by Sparda991** [Ilya114/Box4Droid#1]
Aftet update x11 cmd works, but start-box86 not found
<details>

![Screenshot_2023-04-22-07-09-02-423_com termux](https://user-images.githubusercontent.com/96723119/233776930-87e0d4f7-efe9-4833-b90a-00a07392d470.jpg)
</details>

**Comment by Ilya114** [comment]
Currently repo WIP, so it can work not correctly now, but start-box86 working for me
UPD: After another test I have this error too, fixed
