### ISSUE TITLE
Hi, can you public how did you setup the rootfs ?

### ISSUE THREAD

**Issue by xDoge26** [Ilya114/Box4Droid#10]
I would like to know what you did

**Comment by Ilya114** [comment]
> I would like to know what you did

Hi, this is a not secret, write me in Telegram: https://t.me/Ilya114UA

**Comment by xDoge26** [comment]
How did you start wine with this ?
`wine explorer /desktop=shell` ?

**Comment by Ilya114** [comment]
> How did you start wine with this ? `wine explorer /desktop=shell` ?

Just started. I`m using this:

`box86 wine explorer /desktop=shell,$res /opt/TFM`
`WINEPREFIX=~/.wine-amd64 box64 wine explorer /desktop=shell,$res /opt/TFM`

**Comment by xDoge26** [comment]
where did you get TFM ?

**Comment by Ilya114** [comment]
> where did you get TFM ?

https://github.com/radzikpwnz/tfm/releases/download/v1.0.1/TFM.exe
