### ISSUE TITLE
X11 no display

### ISSUE THREAD

**Issue by Sparda991** [Ilya114/Box4Droid#3]
Every command works. I dont want to annoy you, just reporting issue.
But termux x11 is in Not Connected state after commands

**Comment by Ilya114** [comment]
Write me in Telegram: @Ilya114UA

**Comment by AndroidModLoader** [comment]
Same. Just a blank black screen

**Comment by Ilya114** [comment]
> Same. Just a blank black screen

Try ctrl+c, then ./startbox64 and show me result

**Comment by Ilya114** [comment]
Closing issue due to lack of response
