### ISSUE TITLE
Warning: no /bin/su available in rootfs!

### ISSUE THREAD

**Issue by SolusMonahus** [Ilya114/Box4Droid#4]
![Screenshot_20230426-221328_Termux](https://user-images.githubusercontent.com/113862634/234681356-d6db5145-5f16-4bf9-bc1e-afa92961811c.png)

**Comment by Ilya114** [comment]
Rootfs currently unavailable due to security issues

**Comment by Ilya114** [comment]
Now, I fixed TFM, so, updated rootfs and now you can install and it will working fine
