### ISSUE TITLE
winetricks tutorial

### ISSUE THREAD

**Issue by sobaee** [Ilya114/Box4Droid#5]
Hello Hero

You did a very great thing.

We all appreciate what you have done, bro

Please provide us winetricks and winetricks amd64 tutorials

I tried to apt install winetricks, but it needed to download a lot of things, please tell me to use your .sh winetricks files 🙏🙏

**Comment by Ilya114** [comment]
Winetricks can using in starting menu (6 option)

**Comment by sobaee** [comment]
Yeah, I noticed that once I downloaded the new great version 🤩

The problem that Winetricks-amd64 started to work but then come back after a while to the starting menu, so can't be used

Is there an issue, or it is just me? 🤔

**Comment by Ilya114** [comment]
> The problem that Winetricks-amd64 started to work but then come back after a while to the starting menu, so can't be used
> 
> Is there an issue, or it is just me? 🤔

What is starting menu? If you mean Box86-64 starting menu, after closing Winetricks it will opened again, you can use Winetricks again by pressing 6 in menu

**Comment by sobaee** [comment]
Yes, bro

Sorry for inconvenience


It worked after 3 or 4 trials


This is great

You saved the future of wine on Android
