### ISSUE TITLE
Unity3D games working on Box64?

### ISSUE THREAD

**Issue by Fl4shb4ng** [Ilya114/Box4Droid#6]

**Comment by Ilya114** [comment]
I don't know about Wine, but in Linux should be work
<details>

![Screenshot_20230428-073447_Chrome](https://user-images.githubusercontent.com/93242944/235055232-1c4d1063-2a59-427e-8387-9c4b0e0bbd92.png)
</details>

**Comment by SolusMonahus** [comment]
No, do not work in wine on box86/64.
