### ISSUE TITLE
Support Wine Staging TkG

### ISSUE THREAD

**Issue by sobaee** [Ilya114/Box4Droid#7]
Could you please add the support to install Staging TkG versions of Wine

We need those patches and additions that always be added to Staging TkG versions of Wine

Thanks

**Comment by Ilya114** [comment]
https://github.com/Frogging-Family/wine-tkg-git/releases
Did you mean this? I don't see new versions, so can't

**Comment by sobaee** [comment]
No

I mean these

https://github.com/Kron4ek/Wine-Builds/releases

We have Wine Staging TkG even until 8.6

**Comment by Ilya114** [comment]
> No
> 
> I mean these
> 
> https://github.com/Kron4ek/Wine-Builds/releases
> 
> We have Wine Staging TkG even until 8.6

Ah. I don`t have plans to update fork now, but will consider your suggestion in a future update. Also, you can install it yourself

**Comment by sobaee** [comment]
Could you please provide the best way to do that?
(Do it myself!!)

**Comment by Ilya114** [comment]
> Could you please provide the best way to do that? (Do it myself!!)

Delete your Wine prefix (/root/wine or /root/.wine-amd64) and all in Wine folder (/root/wine-x86 or /root/wine-amd64) then download and unpack need Wine version to /root/wine-x86 or /root/wine-amd64

**Comment by sobaee** [comment]
Thanks a lot

It has installed and worked

The problem that Termux-x11 is disconnected suddenly, so a black screen is produced until restart the proot

I hope you have a fix for this issue

**Comment by Ilya114** [comment]
> The problem that Termux-x11 is disconnected suddenly, so a black screen is produced until restart the proot

Idk, working for me fine

**Comment by sobaee** [comment]
Did you try to update wine to 8.x? (Esp. amd64, I didn't try x86)

This issue is only produced with 8.x 

It doesn't occur with wine7.20

I tried 10 versions of Wine, but this only occurs with Wine8.x

**Comment by sobaee** [comment]
I think this issue will be there if you change the Wine to whatever version or type!

Please, look at it

**Comment by Ilya114** [comment]
I made a decision not add Staging Wine now. 



> Did you try to update wine to 8.x? (Esp. amd64, I didn't try x86)

I`m currently work over other things, but one people have working Wine 8.2. And please, don't write in closed issue

**Comment by sobaee** [comment]
But bro

Stable Wine 8.0.1 has the same issue!

It is not just staging Wines, any Wine other than the default one of yours will cause this issue

**Comment by sobaee** [comment]
Well done llya114

Thanks a lot

Everything is working now (after your last updated release, yesterday)

No more Termux-x11 disconnect with stable or staging wine

This is appropriated

**Comment by Ilya114** [comment]
I thought again and decided to add a choice between Wine builds
