### ISSUE TITLE
winetricks GUI not working well

### ISSUE THREAD

**Issue by stredohori1** [Ilya114/Box4Droid#8]
After choosing winetricks GUI from main menu, GUI isn't showing correct, many winetricks cannot be installed. This is happenning in any x86 Wine (x64 not tested).
Termux screen:
![Screenshot_20230429_211256](https://user-images.githubusercontent.com/130311769/235320572-c621c3db-81fd-424a-9a04-da1478c6f25d.jpg)

Termux-X11 screen:
![Screenshot_20230429_211322](https://user-images.githubusercontent.com/130311769/235320623-6480ace2-06e9-47b6-bcd6-be37f027c737.jpg)

**Comment by Ilya114** [comment]
> Termux-X11 screen: ![Screenshot_20230429_211322](https://user-images.githubusercontent.com/130311769/235320623-6480ace2-06e9-47b6-bcd6-be37f027c737.jpg)

There is a normal
